language: go
go:
  - "1.11"
  - "1.10"
  - "1.9"

before_install:
  - go get -u -v github.com/golang/lint/golint

script:
  - diff -u <(echo -n) <(gofmt -s -d ./) || true
  - diff -u <(echo -n) <(go vet ./...)
  - diff -u <(echo -n) <(golint)
  - go test -v -race ./...